//
//  Wallet.swift
//  
//
//  Created by Thomas Rademaker on 7/8/22.
//

public struct Wallet: Codable {
    /// Used when generating app private keys, which encrypt app-specific data
    let salt: String
    
    /// The private key associated with the root of a BIP39 keychain
    let rootKey: String
    
    /// A private key used to encrypt configuration data
    let configPrivateKey: String
    
    /// The encrypted secret key
    let encryptedSecretKey: String
    
    /// A list of accounts generated by this wallet
    let accounts: [Account]
}
